"""Add CBSA Steel Derivative Goods Surtax tables

Revision ID: 35e71709ec36
Revises: 
Create Date: 2026-02-17 20:50:27.734757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e71709ec36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_origin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('surtax_applicable', sa.Boolean(), nullable=False),
    sa.Column('surtax_rate', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code')
    )
    op.create_table('hs_code_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hs_code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('base_duty_rate', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.Column('surtax_rate', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hs_code')
    )
    op.create_table('province_tax_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province_code', sa.String(length=2), nullable=False),
    sa.Column('province_name', sa.String(length=100), nullable=False),
    sa.Column('tax_type', sa.String(length=10), nullable=False),
    sa.Column('tax_rate', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('province_code')
    )
    op.create_table('surtax_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('ship_date', sa.Date(), nullable=False),
    sa.Column('country_origin_id', sa.Integer(), nullable=False),
    sa.Column('province_code_id', sa.Integer(), nullable=False),
    sa.Column('total_customs_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_duty', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_surtax', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_pst_hst', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_amount_due', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('surtax_applicable', sa.Boolean(), nullable=True),
    sa.Column('importer_name', sa.String(length=200), nullable=True),
    sa.Column('broker_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['country_origin_id'], ['country_origin.id'], ),
    sa.ForeignKeyConstraint(['province_code_id'], ['province_tax_rate.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_table('surtax_line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surtax_order_id', sa.Integer(), nullable=False),
    sa.Column('hs_code_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('customs_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('duty_rate', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('duty_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('surtax_rate', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('surtax_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('pst_hst_rate', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('pst_hst_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['hs_code_id'], ['hs_code_rate.id'], ),
    sa.ForeignKeyConstraint(['surtax_order_id'], ['surtax_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surtax_line_item')
    op.drop_table('surtax_order')
    op.drop_table('province_tax_rate')
    op.drop_table('hs_code_rate')
    op.drop_table('country_origin')
    # ### end Alembic commands ###
